services:
  smart-water-bottle-backend:
    container_name: Smart-Water-Bottle-Backend
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env